### ISSUE TITLE
[Not an issue]: A request

### ISSUE THREAD

**Issue by sa0sin** [ChristopherSchultz/fast-file-count#5]
Hi Chris,

Would it be possible to add count of files and count of subdirs + size recursively ?
To get something like:

path ; #localsubfiles ; #localsubdirs ; localsize ; #totalsubfiles ; #totalsubdirs ; totalsize
dir1;0;10;0;5345;701;45606003
dir1/dir11;10;3;133342;234;28;345660
dir1/dir12;1;6;42;23657;333;35660
...

Regards

**Comment by ChristopherSchultz** [comment]
Sure, it would be possible, but I'm unlikely to add it to fast-file-count for two reasons:
1. It's expanding the program beyond its original scope ("count files")
2. It will complicate the code, which is supposed to be a readable demonstration of a fast, portable, directory-scanning technique

Therefore, I'm going to close this issue.
