### ISSUE TITLE
Brew formula?

### ISSUE THREAD

**Issue by timsutton** [ChristopherSchultz/fast-file-count#6]
Hey, I've found this utility very useful and thought it might make a good addition to Homebrew. Would you have any qualms with me submitting this to brew as a new formula?

**Comment by ChristopherSchultz** [comment]
Timothy,

On 9/22/20 10:30, Timothy Sutton wrote:
> Hey, I've found this utility very useful and thought it might make a
> good addition to Homebrew. Would you have any qualms with me submitting
> this to brew as a new formula?

No qualms at all. I've got a Mac here so I can even test it :)

-chris

**Comment by timsutton** [comment]
I guess submitting this to brew directly would not be possible yet, the local audit complains about this:

```
* GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

a quick Googling suggests other projects have run into the same thing: https://github.com/Homebrew/homebrew-core/pull/35633.

It also would warrant some stable tagged version, as per the [cookbook](https://docs.brew.sh/Formula-Cookbook):

> has a stable, tagged version (i.e. not just a GitHub repository with no versions)

**Comment by ChristopherSchultz** [comment]
Tim,

I can’t do much about the project karma.

I can probably “release” the project, but it would be a source-only release because building a binary wouldn’t make sense really for anybody. 

Thanks,
-chris

**Comment by timsutton** [comment]
Agreed - although if you'd be willing to decide a version (0.0.1, 1.0.0, etc., whichever seems appropriate to you) and push a tag for the state of the repo as of today, then that'd eliminate at least one barrier if in the future we can get it into the default `core` formula repo.

For now I'd probably make the formula on a personal tap and maybe someday in the future I can migrate that formula into the main repo. Since so far, I haven't found another tool that is built to just do this one simple task as fast as possible.

**Comment by timsutton** [comment]
Just to close the loop, I wrote up a formula on my personal tap here: https://github.com/timsutton/homebrew-formulae/blob/master/fast-file-count.rb

I'll close this issue since I don't think there's really any actionable to make it possible yet to get this utility into the main homebrew-core tap.
