### ISSUE TITLE
Fast is relative

### ISSUE THREAD

**Issue by ewilts** [ChristopherSchultz/fast-file-count#7]
We regularly deal with very large NFS-based directories.  These are on very, very fast NFS servers (multiple 100Gbps connections) serving thousands of clients and regularly hit >500K IOPS.

For a directory tree with 2,950,916 files and 232,782 directories, this took:

real	23m20.367s
user	0m2.605s
sys	1m26.131s

I had to delete a directory tree with 40M files yesterday so 3M isn't even all that large here.

**Comment by ChristopherSchultz** [comment]
Sounds like a complaint about NFS speeds and not a bug report.

"Fast is relative".... to what? What other tool are you using that can list files faster than this one?
