### ISSUE TITLE
sort order

### ISSUE THREAD

**Issue by axsweet** [ChristopherSchultz/fast-file-count#8]
Amazing work.  Glad you crushed it.  I removed the debug lol but I ripped it up a little bit because I wanted to count all folders in each sub directory. Worked flawless and its about 2x as fast as my find with sub find loops in bash(way more code on yours but no big deal!)

opendir does that guarantee any sort order?  I was thinking id just read in the time then sort at the end as it should not effect performance really to get the extra info. Any other thoughts? Is there an innate function that determines read order?

The initial directory listing (ls or find etc) is nearly an instant result its a SMB share so to get all the files and details was what really took longer.  I can with out performance do it via bash but....just looking if you had any real slick ideas besides the methods I thought. (I only need that top level date).

A

**Comment by ChristopherSchultz** [comment]
Hey there. This isn't so much of an "issue" as a few questions.

No, `opendir` (really `readdir`) does not sort files. Why would it? Sort them based on what criteria?

The sorting isn't what takes the time, anyway. It's reading the extra information from the filesystem. Different filesystems store that information in different places. The C library only guarantees that certain information will be available from certain calls. It's up to the filesystem driver and the C library to decide if separate e.g. `readdir` and `stat` calls go to the hardware or not.

The only suggestion I got to make things go faster was to make direct Linux kernel calls. While that may be "faster", it's way less portable and part of this project was to demonstrate clean, portable C code. The "problem" with `find`, `ls`, etc. is that they are doing way more than is necessary to simply count files. If all you want to do is count files as fast as possible, a custom-built program is the way to go. Shaving off 0.05% of execution time by working-around the C library doesn't seem worth it to me.
